name: CI + CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Nome do hostname:'     
        required: true
        default: 'gateway-mobile.load.mgensuite.com'    
      duracao:
        description: 'Tempo de duração:'     
        required: true
        default: '300'
      threads:
        description: 'Qtd de threads:'     
        required: true
        default: '1'
      rampup:
        description: 'Qtd de rampup:'     
        required: true
        default: '1'        
      loops:
        description: 'Qtd de Loops:' 
        default: '1'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: igorolivei/github-actions-deploy:latest
    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'employee.json'
      env:
        Parameters.username: ${{github.event.inputs.hostname}}
        Parameters.threads": ${{github.event.inputs.threads}}
        Parameters.url: https://github.com/${{github.repository}}
    
    - name: test kubectl
      run: |
        kubectl version
