name: CI + CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Nome do hostname:'     
        required: true
        default: 'gateway-mobile.load.mgensuite.com'    
      duracao:
        description: 'Tempo de duração:'     
        required: true
        default: '300'
      threads:
        description: 'Qtd de threads:'     
        required: true
        default: '1'
      rampup:
        description: 'Qtd de rampup:'     
        required: true
        default: '1'        
      loops:
        description: 'Qtd de Loops:' 
        default: '1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'employee.json'
      env:
        username: .Parameters.${{github.event.inputs.hostname}}
        url: .Parameters.https://github.com/${{github.repository}}
  
#   printInputs:
#     runs-on: ubuntu-latest
#     steps:
#     - run: |
#         echo "Hostname: ${{ github.event.inputs.hostname }}"    
#         echo "Duração: ${{ github.event.inputs.duracao }}"
#         echo "Threads: ${{ github.event.inputs.threads }}" 
#         echo "Rampup: ${{ github.event.inputs.rampup }}"
#         echo "Loops: ${{ github.event.inputs.loops }}"         
